Openssl ver compatabilty check
siemens/gencmpclient pull request #67
Opened 2024-10-16 09:18 UTC by rajeev-0

## Motivation

issue #46 

## Proposed Changes

Add new CI pipeline.

## Test Plan

Test is not required

2024-11-07 09:43 UTC, DDvO commented
Would this work if rebased on #68?

2025-01-16 17:58 UTC, DDvO requested changes
Looks nice.
Some small points for improvements.

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +          mkdir build-with-libcmp
please add newline before, for better visual grouping

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +          DESTDIR=tmp make install uninstall
Please also add 
```
cd ..

make -f Makefile_v1 test_Mock
```

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +name: OpenSSL compatabilty
```suggestion
name: OpenSSL compatibilty
```

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +name: macos-CI
```suggestion
name: macOS
```

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +          make
Please add and simple test call that the client can load and run, e.g.
```
./cmpClient -help
```

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +          mkdir build
please add newline before, for better visual grouping

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +          sudo make install_sw install_ssldirs
```suggestion
          ./Configure shared --debug --strict-warnings
          make -s -j4
```

2025-01-16 17:58 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +          USE_LIBCMP=1 STATIC_LIBCMP=1 make -f Makefile_v1 build_no_tls
please add: 
```
make -f Makefile_v1 test_Mock
```

2025-01-17 08:30 UTC, DDvO commented on .github/workflows/mac-compatability.yml
> +          DESTDIR=tmp make install uninstall
Argh, with macOS the HTTP-based tests hand, I believe due to waiting for interactive approval for the server to receive input on a local port.

If we do not quickly find way of fixing this, I suggest replacing
```
make -f Makefile_v1 test_Mock`
```
by just
```
make -f Makefile_v1
./cmpClient --help
```

2025-01-17 08:39 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +name: OpenSSL compatibilty
Oh, there is a 2nd typo.
compatibilty -> compatibility

2025-01-17 08:40 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +          ./cmpClient -help
Please add a blank line thereafter (for readability of the grouping).

2025-01-17 08:48 UTC, DDvO commented
One of the two typos is also in the file name `version_compatability.yml`.
Anyway, better include "OpenSSL" in the name, and may simply leave out that difficult word "compatibility",
e.g. `OpenSSL_versions.yml`.

2025-01-17 08:55 UTC, DDvO commented on .github/workflows/version_compatability.yml
> +          USE_LIBCMP=1 STATIC_LIBCMP=1 make -f Makefile_v1 build_no_tls
I believe the current build failure is due to consistency of the build configuration after 
`USE_LIBCMP=1 STATIC_LIBCMP=1 make -f Makefile_v1 build_no_tls`.

So instead of adding `make -f Makefile_v1 test_Mock` thereafter,
one could replace the earlier `make -f Makefile_v1` by `make -f Makefile_v1 test_Mock`.
or insert `make -f Makefile_v1 clean_all` before the mock test build,
of more efficiently: 
augment the new `make -f Makefile_v1 test_Mock` by
`USE_LIBCMP=1 STATIC_LIBCMP=1 make -f Makefile_v1 test_Mock`

2025-01-20 15:07 UTC, DDvO requested changes

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +# GitHub Actions for genCMPClient
I suggest calling the file simply `macos.yml`.

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +          DESTDIR=tmp make install uninstall
```suggestion
          DESTDIR=tmp make install uninstall.  # implies "make build"
          make clean_all
```

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +          ./cmpClient -help
```suggestion
          ./cmpClient -help
          # make -f Makefile_v1 test_Mock  # TODO add after solving issue with CMP HTTP server hanging on startup 
```

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          USE_LIBCMP=1 STATIC_LIBCMP=1 make -f Makefile_v1
```suggestion
          make -f Makefile_v1
          ./cmpClient -help
```

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +        if: matrix.branch == 'openssl-3.0'
```suggestion
        if: matrix.branch == 'openssl-3.4'
```

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +        #TODO: Remove the if condition once the issue is resolved
```suggestion
        #TODO: Remove the condition once is issue is resolved
```
Please also say what the issue is.

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +
I think we can leave this variation out since it is already checked by the normal build CI
and there is no special OpenSSL dependency here.

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +          make clean build
```suggestion
          make
          ./cmpClient -help
```

2025-01-20 15:07 UTC, DDvO commented on .github/workflows/mac-compatibility.yml
> +          make clean build
```suggestion
          make
          ./cmpClient -help
```

2025-01-22 15:45 UTC, DDvO requested changes
for some reason, `steps.cache-openssl.outputs.cache-hit`
seems to nave yield 'true'.
I suggest printing the actual value to help find out what went wrong.

2025-01-22 15:45 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +
better do 
```
echo "OPENSSL_DIR=./${{ matrix.branch }}" >> $GITHUB_ENV
```
already here and use it below, for consistency.

2025-01-22 15:45 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          echo "OPENSSL_LIB=./${{ matrix.branch }}/lib64" >> $GITHUB_ENV
```suggestion
          echo "OPENSSL_LIB=./${{ env.OPENSSL_DIR }}/lib64" >> $GITHUB_ENV
```

2025-01-22 15:45 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          ./config --banner=Configured --debug --strict-warnings --prefix=${PWD}/../${{ matrix.branch }}  shared zlib
```suggestion
          ./config --banner=Configured --debug --strict-warnings --prefix=$${{ env.OPENSSL_DIR }}  shared zlib
```

2025-01-23 12:45 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          echo "LD_LIBRARY_PATH=${{ env.OPENSSL_DIR }}/lib64:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
```suggestion
          echo "LD_LIBRARY_PATH=${{ env.OPENSSL_LIB }}:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
```

2025-01-23 12:48 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          make -f Makefile_v1 clean
Please add a commented-out `make -f Makefile_v1 test_Mock` with a note why it is disabled for now,
and an issue such that we do not forget fixing this later.

2025-01-23 12:48 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +          make deb
Please place before the `make` section

2025-01-23 12:50 UTC, DDvO commented on .github/workflows/OpenSSL_versions.yml
> +  openssl_version:
Please shorten to `version` since `openssl-3.0` etc gets added to the name anyway on CI run.

2025-01-23 12:55 UTC, DDvO commented on .github/workflows/macos.yml
> +          # make -f Makefile_v1 test_Mock  # TODO add after solving issue with CMP HTTP server hanging on startup
Please also mention the `macOS` part in the new issue such that we do not forget fixing this later.

2025-01-23 15:20 UTC, rajeev-0 commented on .github/workflows/OpenSSL_versions.yml
> +          echo "LD_LIBRARY_PATH=${{ env.OPENSSL_DIR }}/lib64:$LD_LIBRARY_PATH" >> "$GITHUB_ENV"
`env` variable is only available in next step. If I use `env.OPENSSL_LIB` here, it will be substituted by blank.

2025-01-23 17:00 UTC, DDvO approved these changes
LGTM

2025-01-23 17:03 UTC, DDvO commented
Ready to merge - 
before doing so, please (auto-squash) each of the two commit threads before, as GitHub does not offer this feature (it can only squash all commits, which is not what we want).

2025-01-24 10:50 UTC, merged